version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: pets
      MYSQL_USER: userland
      MYSQL_PASSWORD: userlandpass
    volumes:
      - mysql:/var/lib/mysql
      - ./sqlmnt:/docker-entrypoint-initdb.d
volumes:
  mysql:
